ENUM_MAP = {
    "weight": {
        "normal": "ft.FontWeight.NORMAL",
        "bold": "ft.FontWeight.BOLD",
        "w100": "ft.FontWeight.W_100",
        "w200": "ft.FontWeight.W_200",
        "w300": "ft.FontWeight.W_300",
        "w400": "ft.FontWeight.W_400",
        "w500": "ft.FontWeight.W_500",
        "w600": "ft.FontWeight.W_600",
        "w700": "ft.FontWeight.W_700",
        "w800": "ft.FontWeight.W_800",
        "w900": "ft.FontWeight.W_900",
    },
    "alignment": {
        "start": "ft.MainAxisAlignment.START",
        "center": "ft.MainAxisAlignment.CENTER",
        "end": "ft.MainAxisAlignment.END",
        "spaceBetween": "ft.MainAxisAlignment.SPACE_BETWEEN",
        "spaceAround": "ft.MainAxisAlignment.SPACE_AROUND",
        "spaceEvenly": "ft.MainAxisAlignment.SPACE_EVENLY",
    },
    "horizontal_alignment": {
        "start": "ft.CrossAxisAlignment.START",
        "center": "ft.CrossAxisAlignment.CENTER",
        "end": "ft.CrossAxisAlignment.END",
        "stretch": "ft.CrossAxisAlignment.STRETCH",
    },
    "vertical_alignment": {
        "start": "ft.CrossAxisAlignment.START",
        "center": "ft.CrossAxisAlignment.CENTER",
        "end": "ft.CrossAxisAlignment.END",
        "stretch": "ft.CrossAxisAlignment.STRETCH",
    },
    "container_alignment": {
        "center": "ft.Alignment.CENTER",
        "topLeft": "ft.Alignment.TOP_LEFT",
        "topCenter": "ft.Alignment.TOP_CENTER",
        "topRight": "ft.Alignment.TOP_RIGHT",
        "centerLeft": "ft.Alignment.CENTER_LEFT",
        "centerRight": "ft.Alignment.CENTER_RIGHT",
        "bottomLeft": "ft.Alignment.BOTTOM_LEFT",
        "bottomCenter": "ft.Alignment.BOTTOM_CENTER",
        "bottomRight": "ft.Alignment.BOTTOM_RIGHT",
    },
    "text_align": {
        "left": "ft.TextAlign.LEFT",
        "center": "ft.TextAlign.CENTER",
        "right": "ft.TextAlign.RIGHT",
        "justify": "ft.TextAlign.JUSTIFY",
    },
    "fit": {
        "contain": "ft.ImageFit.CONTAIN",
        "cover": "ft.ImageFit.COVER",
        "fill": "ft.ImageFit.FILL",
        "fitWidth": "ft.ImageFit.FIT_WIDTH",
        "fitHeight": "ft.ImageFit.FIT_HEIGHT",
        "none": "ft.ImageFit.NONE",
    },
    "scroll": {
        "none": "None",
        "auto": "ft.ScrollMode.AUTO",
        "always": "ft.ScrollMode.ALWAYS",
        "hidden": "ft.ScrollMode.HIDDEN",
    },
}